### ISSUE TITLE
哥哥GUI加个缩放，屏幕要爆了

### ISSUE THREAD

**Issue by Yattoo** [W01fh4cker/Serein#12]

**Comment by W01fh4cker** [comment]
打开你的Serein.py，找到如下代码（目前这个版本是在`65`-`69`行）：
```python
width = window.winfo_screenwidth()
height = window.winfo_screenheight()
window.geometry(f'{width}x{height}')
window.resizable(0, 0)
```
把它修改为：
```python
window.geometry('1920x1080')
```
`1920`和`1080`可以根据自己的分辨率来调整，注意中间是小写字母`x`。

**Comment by Yattoo** [comment]
哦哦 谢谢哥哥！

**Comment by xzajyjs** [comment]
确实需要增加一个GUI缩放，这个调整的是外框的大小且没有滚动条直接就裁切了

**Comment by W01fh4cker** [comment]
> 

有好几个小伙伴和我反馈这个问题了，我还没mac，还没进行测试；目前Serein基本不再维护，重心转移到Karlin的身上。karlin(http://github.com/W01fh4cker/Karlin)，前端采用vue，后端python，这样跨平台很方便。
