### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by ghost** [W01fh4cker/Serein#14]
首先感谢大佬的无私奉献，但是，小弟有一个建议，可否加一个任务进程，可以直观看到已经完成的数量和剩余的数量

**Comment by W01fh4cker** [comment]
我之前也想过要增加进度条，但是尝试之后发现python实现进度条最好的方式还是在命令行，图形化的情况下不太好实现。如果有知道tkinter实现实时进度条的兄弟可以直接加我微信W01fh4cker私聊我，不甚感激！
