### ISSUE TITLE
mac下dll报错

### ISSUE THREAD

**Issue by gonghar** [W01fh4cker/Serein#15]
具体报错信息：
Traceback (most recent call last):
  File "/Users/coke/Desktop/Serein-main/Serein.py", line 75, in <module>
    ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
AttributeError: module 'ctypes' has no attribute 'windll'
是在windows下运行好一些么

**Comment by W01fh4cker** [comment]
这个软件目前支持windows和Linux，mac的话csdn上面有配置文章，但是我没有尝试过，我目前没mac电脑。

**Comment by xzajyjs** [comment]
> 具体报错信息： Traceback (most recent call last): File "/Users/coke/Desktop/Serein-main/Serein.py", line 75, in ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid) AttributeError: module 'ctypes' has no attribute 'windll' 是在windows下运行好一些么

注释以下两行即可
```python
myappid = "W01f.Serein.1.0"
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
```
