### ISSUE TITLE
建议一把梭后问题的汇总或高亮

### ISSUE THREAD

**Issue by weifn00** [W01fh4cker/Serein#19]
漏洞一把梭后，建议把存在的漏洞在最后汇总出来，或者在检测中途发现的时候用高亮显示，提高批量效率的可观性

**Comment by W01fh4cker** [comment]
`python`的图形化非常的不方便，高亮、进度条这些功能都无法实现，至少我目前还不知道如何实现，因此我的新工具`Karlin`会用`Vue`写前端，`python`作为后端，这样就可以解决这些问题

**Comment by weifn00** [comment]
大佬太强了，带带弟弟吧

**Comment by W01fh4cker** [comment]
如果你会`Vue`或者`Python`的话，可以加我微信`W01fh4cker`，欢迎加入到项目中来。
