### ISSUE TITLE
No module named 'ttkbootstrap.constants'

### ISSUE THREAD

**Issue by F6JO** [W01fh4cker/Serein#2]
你好师傅，ttkbootstrap是哪个版本的，我安装最新版本会报错找不到constants
<img width="678" alt="image" src="https://user-images.githubusercontent.com/64877810/175261687-ce8f9c63-fda8-4654-9e3d-39201ebd0d2a.png">

**Comment by W01fh4cker** [comment]
我的`python`版本是3.9.13，`ttkbootstrap`版本是1.7.7。如果还是不行可以加我微信W01fh4cker看看。

**Comment by zym16621** [comment]
也遇到了同样的问题

**Comment by W01fh4cker** [comment]
> 也遇到了同样的问题

目前`Serein`已经停止更新；并且`Serein`只支持`Windows`系统。如果问题还是没有解决，可以加我微信`W01fh4cker`详聊。
