### ISSUE TITLE
问题求教

### ISSUE THREAD

**Issue by 0x1ang** [W01fh4cker/Serein#24]
漏洞利用模块支持自行导入URL吗？

**Comment by W01fh4cker** [comment]
支持，在`Serein.py`的同级目录新建文件：`修正后的url.txt`，然后在里面以`http://www.a.com`的格式（注意`url`末尾不要加`/`）一行一个写入即可。

**Comment by 0x1ang** [comment]
hunter查询为什么会产生如下报错，我的时间格式和给的提示是一样的
【×】出错了！报错内容：'NoneType' object is not subscriptable，如果您无法解决，请立即联系微信W01fh4cker！
【×】起始/结束时间参数格式错误，格式应为2021-07-17 00:00:00

**Comment by W01fh4cker** [comment]
问问题的时候可以附上截图

**Comment by 0x1ang** [comment]
<img width="960" alt="屏幕截图 2022-09-11 192811" src="https://user-images.githubusercontent.com/110606495/189524947-07e5376c-ffef-4e2c-9932-255f14af9815.png">
截图是这样的

**Comment by W01fh4cker** [comment]
从图片上看可能的问题有：
- 你的`Hunter`的`api-key`和`cookie`中至少有一个填错了；
- 命令行原本有报错，需要重启之后再尝试；
- 你的电脑开了代理。   



如果这些都不是，请联系微信`W01fh4cker`远程查看。
