### ISSUE TITLE
可否新增shadan查询接口

### ISSUE THREAD

**Issue by value-0** [W01fh4cker/Serein#9]
可否新增shadan查询接口，以及结果自定义保存，谢谢

**Comment by W01fh4cker** [comment]
我在`6`月`21`日的时候实现了`Shodan`查询，参考：https://github.com/W01fh4cker/Serein/blob/main/version.md；
结果自定义保存我不太明白是什么意思，因为我对`Serein`的定位不是一款搜索工具；`Serein`的应用场景是：对采集的网站（比如说`10000`个网站）进行某一漏洞的批量探测以及权重查询，以达到提交`src`的效果；如果您想要搜索、保存的话，可以参考我朋友的https://github.com/xzajyjs/ThunderSearch 以及`github`上面的综合工具https://github.com/atdpa4sw0rd/Search-Tools ，他们都是非常好的开源项目；如果您还有什么问题，可以继续追问；如果您的问题非常紧急，可以加我的微信W01fh4cker。感谢您的提问！
